workflows:
  flutter-app:
    name: Over the Bike Fit
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/app/outputs/flutter-apk
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
