workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate App Icons
        script: |
          # 폴더가 없어도 빌드가 멈추지 않게 || true를 붙입니다.
          flutter pub run flutter_launcher_icons || true
      - name: Flutter build APK
        script: |
          # Gradle 프로젝트 에러를 방지하기 위해 강제 빌드 시도
          flutter build apk --release --build-name=1.0.1 --build-number=7
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
