workflows:
  android-workflow:
    name: Bike Fit Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project
        script: |
          flutter clean
          flutter create --platforms android .
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: |
          # 빌드 번호를 300으로 대폭 상승
          flutter build apk --release --build-name=1.3.0 --build-number=300
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
