workflows:
  over_the_bike_fit:               # ← 이 이름으로 바꾸면 프로젝트 이름과 딱 맞아서 인식률 최고
    name: Over The Bike Fit Build
    instance_type: mac_mini_m2
    max_build_duration: 45

    environment:
      flutter: stable

    scripts:
      - flutter pub get

      - |
        # Gradle 강제 호환 (android 폴더 없이 해결)
        mkdir -p android/gradle/wrapper
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-all.zip" > android/gradle/wrapper/gradle-wrapper.properties
        echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties

      - flutter clean
      - flutter build apk --release --split-per-abi

    artifacts:
      - build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
