workflows:
  android-workflow:
    name: Bike Fit Final Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project
        script: flutter create --platforms android .
      - name: Get Packages
        script: flutter pub get
      - name: Build APK
        script: |
          # 빌드 번호를 120으로 올려서 아이콘/스플래시가 폰에 강제 적용되게 함
          flutter build apk --release --build-name=1.1.0 --build-number=120
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
