workflows:
  android-workflow:
    name: Bike Fit Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          unzip *.zip
          PROJ=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ"
          # 이미지 파일 강제 복사
          mkdir -p assets
          cp ../assets_final/*.png ./assets/ 2>/dev/null || true
          # 빌드 실행
          flutter create . --platforms android
          flutter pub get
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
