workflows:
  android-workflow:
    name: Over the Bike Fit Android
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/app/outputs/flutter-apk
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
