workflows:
  android-workflow:
    name: Android Release Build
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean and Recreate Android Folder
        script: |
          # 기존 꼬인 설정을 삭제하고 안드로이드 빌드 환경을 강제 생성합니다.
          rm -rf android
          flutter create --platforms android .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --clean
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
