workflows:
  flutter-android-release:
    name: Bike Fit Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Setup
        script: |
          unzip *.zip
          PROJ=$(find . -maxdepth 1 -type d -not -path '.*' | head -n 1)
          cd "$PROJ"
          flutter create . --platforms android
          flutter pub get
      - name: Build
        script: |
          PROJ=$(find . -maxdepth 1 -type d -not -path '.*' | head -n 1)
          cd "$PROJ"
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
