workflows:
  android-release:
    name: OverTheBikeFit Build
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project and Inject Permissions
        script: |
          flutter create --platforms android .
          
          # AndroidManifest.xml의 아이콘 경로를 @mipmap/ic_launcher로 통일
          mkdir -p android/app/src/main
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
              <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <application
                  android:label="OverTheBikeFit"
                  android:name="\${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <meta-data android:name="flutterEmbedding" android:value="2" />
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Get packages and Generate Assets
        script: |
          flutter pub get
          flutter pub run flutter_launcher_icons:main
          flutter pub run flutter_native_splash:create
      - name: Build APK
        script: |
          # 빌드 번호를 높여서 확실히 구분 (3000)
          flutter build apk --release --build-name=3.0.0 --build-number=3000
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
