name: BikeFit PlayStore Stable Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      - name: Fix Flutter V1 Embedding
        run: |
          find android -name "*.kt" -type f -exec sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' {} +

      - name: Install dependencies
        run: flutter pub get

      - name: Restore Keystore
        env:
          KEY_DATA: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          mkdir -p android/app
          echo "$KEY_DATA" | tr -d '\n ' | base64 --decode > android/app/release.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=release.jks
          EOF

      - name: Build AAB
        run: flutter build appbundle --release --build-number=1005

      - name: Verify SHA1
        run: |
          echo "Expected SHA1: 75:CD:32:95:21:A1:35:86:C6:33:E7:ED:4E:F6:87:37:E2:D9:FD:3D"
          echo "Actual SHA1:"
          keytool -printcert -jarfile build/app/outputs/bundle/release/app-release.aab | grep SHA1

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: BikeFit-AAB
          path: build/app/outputs/bundle/release/app-release.aab
